name: hearme
description: "HearMe - Mental Health & AI Medical Chatbot"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  jwt_decoder: ^2.0.1
  record: ^6.0.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFF3ED"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
